### ISSUE TITLE
Actively start work on a comms fix - or consider GoLang rewrite

### ISSUE THREAD

**Issue by openhardwarecoza** [LaserWeb/lw.comms#2]
I have decided its about time I learn a new language, and GoLang seems to be the easiest way to go and still keep easy momentum from Nodejs work...

For example, GoLang has a socket.io library 	"github.com/googollee/go-socket.io" so our frontend can stay mostly the same

For now I am developing with lw.comms and laserweb3 repos in the same directory:

![repo](https://cloud.githubusercontent.com/assets/7695323/20700721/ad3fd7f8-b617-11e6-86b3-ef4bb5e73edb.PNG)

So the webserver in server-smoothie.go hosts the HTML from ../LaserWeb3/public  - why - well it forces me to make sure any changes I need to make is updated in the nodejs side too. For example, go-socket-io needs all lowercase event names, so I had to apply this change in socketcomms.js, and thus also in the nodejs servers: https://github.com/LaserWeb/LaserWeb3/commit/351ce5da67945fa467ec98af866a324e7757be9a

So, so far I have the following implemented:

1.  The app starts and hosts a local webserver (just like we did with node static in the nodejs servers)
2.  It also hosts a socket.io server (just like the nodejs servers)
3.  I have it listening for socket.io events.  (just like node) - right now I just console log them out when a message is received. The next part of the job is of course now to add the meat to the bones. namely, serialport functionality! Lots to port from the nodejs side @cprezzi @Cinezaster

**Comment by openhardwarecoza** [comment]
@lautr3k  (: if you get bored with frontend, this needs help too)

**Comment by cprezzi** [comment]
I was allready thinking of combining the node servers too make it easyer for the user. The server only has to detect the connected firmware to select the right variant.

**Comment by openhardwarecoza** [comment]
Agreed on that too.  I used to do exactly that in LW1

**Comment by jorgerobles** [comment]
Hi Peter, does this change have anything related to lw4? I mean that having
two different toolchains in that case is not my preference. I think Node as
frontend tool, and as a server/electron app backend is better, on
development, documentation and deployment.

:)

**Comment by openhardwarecoza** [comment]
https://github.com/LaserWeb/LaserWeb/blob/master/server.js#L259-L357

**Comment by openhardwarecoza** [comment]
@jorgerobles we've given Electron all the chance it deserves and cannot get it working reliably with Windows https://github.com/LaserWeb/LaserWeb3/pull/154#issuecomment-252776691 so unless there is new news I am not aware of, something needs to be done to stop users from having to go through this heartache https://plus.google.com/u/0/102159396139212800039/posts/JN7LGztSrkJ?sfc=true

![node compil](https://cloud.githubusercontent.com/assets/7695323/20701895/feeeb26c-b61d-11e6-8255-54523c602e7b.PNG)

GoLang works well for the SPJS project (of course the rest of SPJS doesnt work so well for us https://github.com/LaserWeb/LaserWeb2/issues/52 being what tipped me over the edge and saying stuff it I'll write my on in node...)

**Comment by openhardwarecoza** [comment]
To elabororate, I dont want this to replace the whole build... this is to replace the serial<->socketio bridge...
I've had enough of node-serialport and its native module problems

**Comment by openhardwarecoza** [comment]
(: I'm not far enough along with the go work for you to not b able to stop me.  All i'm saying we all love working on the frontend. Its fun, its pretty. But the comms and distributability needs real work and it needs it sooner than later

**Comment by cprezzi** [comment]
Before implementig a new lw.comms module we should first define a uniform socket interface for the client. This interface has to unify all the small differences of the differnt firmwares to one command set.

**Comment by kaosat-dev** [comment]
I have to agree with @jorgerobles on avoiding multiple toolchains whenever possible.
But yeah node-serialport does not have a very good track record. Although , (a shot in the dark) was there no luck with something like node-pregyp (if memory serves right) to keep a good set of native modules ?

**Comment by cprezzi** [comment]
What was the problems with node installation and serial? I never had any problem with installation on Windows on different machines.

**Comment by jorgerobles** [comment]
Hi Peter.
Ok, I see your point about serial-socket.io but I'm not so sure about
electron... and the notElectron related deployment issues.
The "users" are downloading a development version of LW. The release should
be an "exe" for windows, with all that problems solved.
I've got some experience from other projects trying to convince the user
that downloading python/compile, etc is the best way, and proved wrong.

We could always provide a docker machine for running the DEV on win.

**Comment by openhardwarecoza** [comment]
Changed the title (: Now that we have some active engagement (: (Yay - I love how we you start something wrong, suddenly the right conversations happen)

Node-gyp does keep precompiled modules, hosted by the node-serial project, for 90% of the cases, but, at least every week or two we have a user who has to reinstall his machine, or try a different PC.  If we had 100000 users, one or two cases would be fine. We currently have 500-+ users according to Google Analytics, which might be realistically half sometimes. 1 failure a week is too much

Secondly, we are going to have the influx of Emblaser and Fabcreator users who are not hackers, are not devs, and honestly whom a commandline is fucking scary to.

The whole npm stack is awesome to people like us. But not to someone used to a MSI / Installshield world.  Click the installer, next next next, click the icon in the Start menu.

Thats what we need! Nothing less

**Comment by kaosat-dev** [comment]
@openhardwarecoza I second @jorgerobles  , in that case  having an installer etc for non techie users makes complete sense, and there is a lot of tooling to make that rather easy with Electron. (I can look up the exact toolchain later , but it is relatively trivial).

**Comment by openhardwarecoza** [comment]
@cprezzi surprisingly often install failures.  Someone accidentally grabbing node 6 instead of 4 for example (and I see node 7 is out http://www.infoworld.com/article/3131601/javascript/nodejs-7-set-for-release-next-week.html so - too fast paced!  )  Thats the thing with Node.  Its hard to install fresh, and hard to stay up to date

**Comment by kaosat-dev** [comment]
nvm for the win to test different node versions :)
Also we might not want to support every single node version, just LTS ?
(node 7 apparently has a lot of issues)

**Comment by openhardwarecoza** [comment]
(: I have no objection against a process to build an installable binary with electron, if you can get node-serialport to work. Read through https://github.com/LaserWeb/LaserWeb3/issues/135 and https://github.com/LaserWeb/LaserWeb3/pull/154

3 Months later and no solution yet...

**Comment by openhardwarecoza** [comment]
@kaosat-dev we have always said LTS, but hey,  an artist in outback australia isnt going to know what LTS means...

**Comment by openhardwarecoza** [comment]
(: Ask your grandma to follow this https://github.com/LaserWeb/LaserWeb3/wiki/Install:-Windows hehe

**Comment by kaosat-dev** [comment]
@openhardwarecoza my bad, sorry !

**Comment by openhardwarecoza** [comment]
No bad... I would love any of you to prove me wrong and give us a working Electron build. Electron having a GUI beats the text only golang too!

**Comment by openhardwarecoza** [comment]
@krolco

**Comment by openhardwarecoza** [comment]
@copet80

**Comment by cprezzi** [comment]
Too fast paced - that's somebody could also say about LW (especially with changing languages and libraries) ;)

**Comment by openhardwarecoza** [comment]
(; Yip I know I am a hyprocryte

I update node to 6 on my PC now, and saw the version of node-serialport in package.json was too old. So updated that too. 

Busy installing electron - so I can play with the Emblaser branch

**Comment by cprezzi** [comment]
@openhardwarecoza : I allways install node 6 (not 4) as described in the very good step by step windows installation guide on the wiki. No problem with that at all.

**Comment by openhardwarecoza** [comment]
```
peter@DESKTOP-7J3RTF9 MINGW32 ~/Documents/Github/LaserWeb3 (master)
$ npm install

> serialport@2.1.2 install C:\Users\peter\Documents\Github\LaserWeb3\node_modules\tinyg\node_modules\serialport
> node-pre-gyp install --fallback-to-build


C:\Users\peter\Documents\Github\LaserWeb3\node_modules\tinyg\node_modules\serialport>if not defined npm_config_node_gyp (node "C:\Users\peter\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )

C:\Users\peter\Documents\Github\LaserWeb3\node_modules\tinyg\node_modules\serialport>if not defined npm_config_node_gyp (node "C:\Users\peter\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\Users\peter\Documents\Github\LaserWeb3\node_modules\tinyg\node_modules\serialport\build\Release\serialport.node --module_name=serialport --module_path=C:\Users\peter\Documents\Github\LaserWeb3\node_modules\tinyg\node_modules\serialport\build\Release )  else (node "" configure --fallback-to-build --module=C:\Users\peter\Documents\Github\LaserWeb3\node_modules\tinyg\node_modules\serialport\build\Release\serialport.node --module_name=serialport --module_path=C:\Users\peter\Documents\Github\LaserWeb3\node_modules\tinyg\node_modules\serialport\build\Release )

C:\Users\peter\Documents\Github\LaserWeb3\node_modules\tinyg\node_modules\serialport>if not defined npm_config_node_gyp (node "C:\Users\peter\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" build --fallback-to-build --module=C:\Users\peter\Documents\Github\LaserWeb3\node_modules\tinyg\node_modules\serialport\build\Release\serialport.node --module_name=serialport --module_path=C:\Users\peter\Documents\Github\LaserWeb3\node_modules\tinyg\node_modules\serialport\build\Release )  else (node "" build --fallback-to-build --module=C:\Users\peter\Documents\Github\LaserWeb3\node_modules\tinyg\node_modules\serialport\build\Release\serialport.node --module_name=serialport --module_path=C:\Users\peter\Documents\Github\LaserWeb3\node_modules\tinyg\node_modules\serialport\build\Release )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\Users\peter\Documents\Github\LaserWeb3\node_modules\tinyg\node_modules\serialport\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\peter\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\peter\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\peter\\Documents\\Github\\LaserWeb3\\node_modules\\tinyg\\node_modules\\serialport\\build\\Release\\serialport.node" "--module_name=serialport" "--module_path=C:\\Users\\peter\\Documents\\Github\\LaserWeb3\\node_modules\\tinyg\\node_modules\\serialport\\build\\Release"
gyp ERR! cwd C:\Users\peter\Documents\Github\LaserWeb3\node_modules\tinyg\node_modules\serialport
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users\peter\Documents\Github\LaserWeb3\node_modules\tinyg\node_modules\serialport\build\Release\serialport.node --module_name=serialport --module_path=C:\Users\peter\Documents\Github\LaserWeb3\node_modules\tinyg\node_modules\serialport\build\Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\peter\Documents\Github\LaserWeb3\node_modules\tinyg\node_modules\serialport\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\peter\\Documents\\Github\\LaserWeb3\\node_modules\\tinyg\\node_modules\\serialport\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\peter\Documents\Github\LaserWeb3\node_modules\tinyg\node_modules\serialport
node-pre-gyp ERR! node -v v6.9.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.26
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users\peter\Documents\Github\LaserWeb3\node_modules\tinyg\node_modules\serialport\build\Release\serialport.node --module_name=serialport --module_path=C:\Users\peter\Documents\Github\LaserWeb3\node_modules\tinyg\node_modules\serialport\build\Release' (1)
laserweb@3.254.0 C:\Users\peter\Documents\Github\LaserWeb3
`-- (empty)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\peter\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.2
npm ERR! code ELIFECYCLE

npm ERR! serialport@2.1.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the serialport@2.1.2 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs serialport
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\peter\Documents\Github\LaserWeb3\npm-debug.log

peter@DESKTOP-7J3RTF9 MINGW32 ~/Documents/Github/LaserWeb3 (master)
$ npm install --save serialport

> serialport@4.0.6 install C:\Users\peter\Documents\Github\LaserWeb3\node_modules\serialport
> node-pre-gyp install --fallback-to-build

[serialport] Success: "C:\Users\peter\Documents\Github\LaserWeb3\node_modules\serialport\build\Release\serialport.node" is installed via remote
laserweb@3.254.0 C:\Users\peter\Documents\Github\LaserWeb3
`-- serialport@4.0.6


peter@DESKTOP-7J3RTF9 MINGW32 ~/Documents/Github/LaserWeb3 (master)
$ node server-smoothie.js

***************************************************************
                 ---- LaserWeb Started ----
***************************************************************
  Access the LaserWeb User Interface:
  1. Open Chrome
  2. Go to :   http://192.168.1.150:8000/
***************************************************************


* Updates:
  Remember to check the commit log on
  https://github.com/openhardwarecoza/LaserWeb3/commits/master
  regularly, to know about updates and fixes, and then when ready
  update LaserWeb3 accordingly by running git pull

* Support:
  If you need help / support, come over to
  https://plus.google.com/communities/115879488566665599508
```

**Comment by openhardwarecoza** [comment]
Well,  this day is over.  Tomorrow I'm on a plane for a hectic two week,  4 city work project thing again.  

I couldnt get electron installed (LIFECYCLE errors)  so didnt get to play with that.  On the golang side i am over my head too.  My hackish way of having var port,  as global var,  and later assigning a real node serialport imstance to it, doesnt work in Go.  It checks all the functions downward during the go build...

**Comment by openhardwarecoza** [comment]
Ok, Electron seems to work now! Glad I could rattle all your cages with a GoScare (: - finally got me the answers I wanted (:

The Node fanboys went: 
![duty_calls](https://cloud.githubusercontent.com/assets/7695323/20752205/b38313d6-b708-11e6-8bc9-3694ceb438c1.png) and now those bugs are solved (;

Happy to have been wrong about Golang (;
